development:
  clients:
    default:
      database: travian_ver3_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false
test:
  clients:
    default:
      database: travian_ver3_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
