puts 'clear farms'

User.first.accounts.first.farm_lists.second.farms.destroy_all

puts 'remake farms ...'

#list cap-farm
User.first.accounts.first.farm_lists.second.farms.create! x: -51, y: 9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -47, y: 33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -45, y: 30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -28, y: -43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -28, y: -52, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -40, y: -28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -40, y: -30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -36, y: -30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -35, y: -31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -35, y: -33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -34, y: -35, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -36, y: -38, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -34, y: -42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -31, y: -42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -47, y: -10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -46, y: -11, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -47, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -41, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -38, y: -17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -34, y: -17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -32, y: -18, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -41, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -34, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -33, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -35, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -31, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -30, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -33, y: 1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -28, y: 0, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -48, y: -2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -45, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -44, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -30, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -43, y: -4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -44, y: 25, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -48, y: 22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -46, y: 20, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -29, y: 20, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -28, y: 19, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -41, y: 16, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -44, y: 14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -32, y: 41, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -38, y: 40, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -36, y: 39, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -34, y: 39, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -39, y: 37, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -47, y: 33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -44, y: 33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -41, y: 31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -37, y: 31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -45, y: 30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -43, y: 30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -38, y: 30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -38, y: 29, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -29, y: 26, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -29, y: 44, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -31, y: 43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -28, y: -43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -21, y: -43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: -43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: -45, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -23, y: -46, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -13, y: -48, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -24, y: -36, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -31, y: -42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -17, y: -42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -26, y: -9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -22, y: -11, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -16, y: -13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -23, y: -14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -21, y: -15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -16, y: -21, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -22, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -18, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -15, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -13, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -20, y: 5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: 4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -15, y: 3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -31, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -30, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -12, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -22, y: 1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -17, y: 1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -28, y: 0, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -30, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -13, y: -4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -26, y: -5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -14, y: -7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -13, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -19, y: 24, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -19, y: 48, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: 47, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -29, y: 44, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -22, y: 44, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -31, y: 43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -26, y: 43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -23, y: 67, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -25, y: 63, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 2, y: -66, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -4, y: -68, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 6, y: -68, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 0, y: -69, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 5, y: -70, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 0, y: -73, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 5, y: -74, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: -43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -9, y: -43, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -3, y: -44, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: -45, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -4, y: -19, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -10, y: -21, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -13, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -10, y: 8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: 4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -12, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -9, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -11, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -13, y: -4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -10, y: -5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -14, y: -7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -13, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -7, y: 21, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -5, y: 21, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -7, y: 19, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 1, y: 17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 3, y: 15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -8, y: 14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -3, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -10, y: 10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: -8, y: 10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 17, y: -78, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 21, y: -79, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 13, y: -80, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 17, y: -80, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 19, y: -81, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 10, y: -82, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 18, y: -82, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 16, y: -83, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 14, y: -85, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 21, y: -65, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 6, y: -68, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 5, y: -70, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 20, y: -70, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 13, y: -73, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 22, y: -73, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 5, y: -74, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 13, y: -75, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 11, y: -76, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 21, y: 18, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 3, y: 15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 16, y: 15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 11, y: 14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 9, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 14, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 15, y: 12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 5, y: 38, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 19, y: 33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 4, y: 31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 3, y: 27, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 20, y: 58, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 4, y: 54, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 13, y: 53, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 23, y: 52, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 6, y: 51, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 21, y: -65, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 36, y: -72, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 22, y: -73, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 25, y: -73, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 30, y: -74, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: -74, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 27, y: -75, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 29, y: -75, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 32, y: -75, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 30, y: -76, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: -76, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 20, y: -44, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 40, y: -27, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 34, y: -11, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 32, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 33, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 33, y: -13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 40, y: -16, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 22, y: 8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 33, y: 7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 33, y: 6, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 34, y: 6, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 36, y: 6, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 30, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 40, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 25, y: 0, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 23, y: -2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 25, y: -2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 31, y: -2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 30, y: 49, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: 48, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 47, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 25, y: 46, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 29, y: 45, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: 45, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: -94, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 45, y: -81, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: -71, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: -74, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: -76, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 41, y: -26, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 40, y: -27, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 45, y: -27, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 50, y: -28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 42, y: -30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: -38, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 46, y: -9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 42, y: -10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 41, y: -15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 42, y: -15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 40, y: -16, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 55, y: -16, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: -17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 53, y: -20, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 49, y: 8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 49, y: 7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: 7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 45, y: 5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: 5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 41, y: 4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 42, y: 4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 52, y: 3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 53, y: 3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 40, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: 1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 42, y: 0, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 53, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 25, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 40, y: 23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: 22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 53, y: 21, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 53, y: 19, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 51, y: 18, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 52, y: 18, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: 15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 50, y: 14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 38, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 42, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 46, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: 12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 49, y: 9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 41, y: 42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 39, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 48, y: 39, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 47, y: 36, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 49, y: 36, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 49, y: 33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 50, y: 33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 50, y: 32, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 41, y: 31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 44, y: 31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: 48, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 37, y: 47, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 39, y: 45, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 44, y: 44, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: -38, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 59, y: -38, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 60, y: -42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 61, y: -10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 65, y: -10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 66, y: -10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 60, y: -11, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 66, y: -11, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 68, y: -11, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 70, y: -13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 69, y: -15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 55, y: -16, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 70, y: -16, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: -17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 67, y: -17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 58, y: -20, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -20, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 63, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 60, y: 8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: 7, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 61, y: 6, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: 5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 60, y: 4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 58, y: 3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 61, y: 3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 58, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 67, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: 1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 61, y: -4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 69, y: -4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -4, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 60, y: -5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 68, y: -5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 69, y: -5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 58, y: -6, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 25, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 57, y: 22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 54, y: 15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 56, y: 9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: 35, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: 29, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: 28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -27, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 80, y: -28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 81, y: -28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -29, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 80, y: -30, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 79, y: -32, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -35, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -36, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -37, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -39, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -40, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -42, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 75, y: -9, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 81, y: -10, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 75, y: -11, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 85, y: -12, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 82, y: -14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 85, y: -15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 79, y: -16, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 81, y: -17, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 78, y: -18, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 80, y: -18, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: -20, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 78, y: -20, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 75, y: -21, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 79, y: -22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 78, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 82, y: -23, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 83, y: -24, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 76, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 83, y: -1, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 72, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -3, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 75, y: -6, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 71, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 77, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 85, y: -8, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: 13, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 73, y: 35, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: 29, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 75, y: 29, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 87, y: 29, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 74, y: 28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 88, y: 28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 91, y: 91, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 101, y: -54, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 93, y: -33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 98, y: -14, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 100, y: 0, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 92, y: 33, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 94, y: 31, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 88, y: 28, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 91, y: 91, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 92, y: 91, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 96, y: 91, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 97, y: 91, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 95, y: 99, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 121, y: -61, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 122, y: -22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 111, y: 5, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 124, y: 59, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 122, y: 58, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 121, y: 73, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 122, y: 73, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 121, y: 78, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 130, y: -26, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 135, y: -32, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 136, y: -32, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 137, y: -32, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 135, y: -34, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 136, y: -34, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 137, y: -15, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 122, y: -22, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 133, y: -25, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 131, y: 2, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 124, y: 59, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 122, y: 58, army4: 25
User.first.accounts.first.farm_lists.second.farms.create! x: 122, y: 73, army4: 25
